### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by carmee-en** [Arquisoft/InciManager_i2b#33]
As we learned on the last laboratory class, for the next week we should have defined some user stories. The implementation is not required for now so the main focus is defining them correctly.

They will be stored in a new wiki entry. After uploading the stories and before closing the issue I will update the thread so one of you can review it.

**Comment by carmee-en** [comment]
First draft uploaded: [wiki entry](https://github.com/Arquisoft/InciManager_i2b/wiki/User-stories)

Alejandro mentioned that the sensor's sending incidents is also important but i didn't know how that could be expressed. As always, any feedback is welcome.

**Comment by alejgh** [comment]
They look good to me in general. I would make just two quick changes to the first two user stories (the ones that describe reporting incidents).

* When the person reports an incident he will not be using any form. Instead he will be using the chat interface, that will ask him the information about the incident, and then the incident will be created. I think this will be hard to test later on, but for now I would replace:
```
AND	THE CITIZEN FILLS THE INCIDENT FORM (?)
AND	THE CITIZEN CLICKS SUBMIT (?)
```
with something like:
```
AND	THE CITIZEN REPORTS THE INCIDENT
AND	THE INCIDENT IS CREATED AND PROCESSED
```
We will worry later about how to test the chat interface (it is being written in Javascript).

* Then, about sensors: A sensor can have a little program for example that sends a POST request to "incident/create" every x minutes and creates an incident, so I would write something like this:
```
AS 		SENSOR
I WANT		TO REPORT INCIDENTS
SO THAT		THE RESPONSE TEAM COMES ASAP

SCENARIO	SENSOR REPORTS AN INCIDENT
GIVEN		THE SENSOR HAS INTERNET CONNECTION
WHEN		THE SENSOR POSTS AN INCIDENT TO '/INCIDENT/CREATE'
THEN		THE INCIDENT IS SENT TO THE INCIDENT DASHBOARD
	AND	THE RESPONSIBLE PERSON VIEWS THE INCIDENT (AND ITS STATE)
```
maybe some more things could be added (for example, the sensor includes in the POST it's login credentials) if the Cucumber tests require so.

* Finally, I don't see it necessary to distinguish if a Person or a Entity is creating the entity, since both are doing the same thing. The only difference on these two tests is the kind of the agent creating the incident. Of course, this is just my opinion, so we can discuss it if you want.

**Comment by carmee-en** [comment]
That makes sense to me. I already updated the wiki with these changes. Also, about entities and people reporting incidents, I asked Labra about it in an email. It seems to me that both should be included. Waiting for a response now.

**Comment by carmee-en** [comment]
No response yet. Closing the issue.
